 
version: '3.8'
services:
  web:
    build: ./fullstack-frontend-react
    container_name: reacttt
    ports: 
      - '3001:3001'

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullstack
      - MYSQL_USER=harsha
      - MYSQL_PASSWORD=harsha
    restart: always
    ports:
      - '3307:3307'
    volumes:
      - mysqldb:/var/lib/mysql
   

volumes:
  mysqldb:


   











